### ISSUE TITLE
Missing references in example

### ISSUE THREAD

**Issue by jorlarsen** [bengeisler/TcLog#12]
Hi, I just installed this via Twinpack and tried to run the example code, but I am missing some references or libraries maybe?

MAX_STRINGLENGTH
Constants.FifoOverhead
LogLevels.Debug

All of these are red and not recognized by Twincat. Is there something I am missing?

**Comment by jorlarsen** [comment]
Update: I guess MAX_STRING_LENGTH is the correct use, but I am still stuck with the other two errors.

**Comment by bengeisler** [comment]
Hi, thanks for reaching out!
I'm on holiday this week and have limited access to the repo. I'll check it in detail next week. 

I guess you're right with `MAX-STRING_LENGHT`. I'll update the documentation. 

I'm not sure about the other two references. They are included in the project und should be in the library on Twinpack as well. 

Could you clone the repo and build the library? The version here on Github is newer than the one one Twinpack.

**Comment by jorlarsen** [comment]
Cloning the repo from GitHub fixed the issue, thanks for your fast reply!

One lib had version 0.2.2 and the other 0.2.2.0 so I thought they were the same at first.

**Comment by bengeisler** [comment]
I'm only updating the version when I'm creating a new release, that's why they are the same. The version on Github is still work-in-progess since I'm currently adopting the Zeugwerk naming conventions. Once I'm finished (soon) I'll create a new release and push it to Twinpack. 

The versions 0.2.2.0 and 0.2.2 should be the same - either Beckhoff or Twinpack required the additional digit, I don't remember which it was. Generally, I stick to semantic versioning and just add the additional `.0` if neccessary. 

I'm glad the issue could be resolved! Feel free to reach out if there are any questions regarding the library 😊
