### ISSUE TITLE
Is there a way to check if the logger is time Synced?

### ISSUE THREAD

**Issue by paulbarron85** [bengeisler/TcLog#17]
What is the best way to write log messages on the first couple of PLC scans after restarting.
I would like to implement something like the following in a POU:
```
VAR_INPUT
	bInput : BOOL;
	bFirstScan : BOOL;
END_VAR
VAR
	_logger : TcLog;
	_tcLogTrig : TcLogTrig;
END_VAR


_logger
	.OnCondition(bFirstScan)
	.Warning(CONCAT('Initial value is ', BOOL_TO_STRING(bInput)));	

_tcLogTrig
	.OnRisingEdge(bInput)
	.Warning('Signal had a rising edge');	
	
_tcLogTrig
	.OnFallingEdge(bInput)
	.Warning('Signal had a falling edge');
```

With the POU being calling like so from MAIN:
```
VAR
	_coreLogger : TcLogCore(bufferSize := 100 * (Tc2_System.MAX_STRING_LENGTH + Constants.FifoOverhead));
	_logger : TcLog;
	
	fbTest : FB_Test;
	bInput : BOOL;
	bFirstScan : BOOL := TRUE;
END_VAR


_coreLogger
.WriteToAds()  
.IncludeInstancePath()
.TimestampFormat('YYMMDD')
.SetRollingInterval(RollingIntervals.Daily)
.MinimumLevel(LogLevels.Debug)
.WriteToFile(path, filename)
.RunLogger();

fbTest(bInput := bInput, bFirstScan := bFirstScan);
bFirstScan := FALSE;
```

However I end up getting two files written as below:
![image](https://github.com/bengeisler/TcLog/assets/40207358/0debd819-f26a-4fcf-827a-5ff00aee18d3)
With the contents of the first file being:
![image](https://github.com/bengeisler/TcLog/assets/40207358/b100c884-f3c1-4d1b-9ebf-0e44a8fc1223)

It looks like the time hasn't been updated yet to the local time. Is it possible to expose DateTime._localSystemTime.bValid? Or is there a better way of doing this?

**Comment by bengeisler** [comment]
The best way would be if the logger buffered these messages until the time is valid and then write them to the file. Since it already has a buffer built-in, this should be easy to implement. It always takes a few cycles until the time information is available. 

Meanwhile, as a workaround, you can just use the `DateTime` function block as dummy because it exposes a `Done` property and trigger your logging once it becomes `true`. The same function block is used internally, so I'd expect the `done` bits to be in sync. See [here](https://bengeisler.github.io/TcLog/reference/TcLog/Utils/DateTime.html#TcLog.DateTime.Done).

I'll look into the buffering as well this weekend.

**Comment by bengeisler** [comment]
As a side note, you could simplify the logic of your first logging by leveraging the built-in string builder and any-to-`string` casts:
```
_logger
	.OnCondition(bFirstScan)
        .AppendString('Initial value is ')
        .AppendAny(bInput)
	.Warning();
```

**Comment by bengeisler** [comment]
This issue has been fixed with the [latest release](https://github.com/bengeisler/TcLog/releases/tag/v0.4.0). 

It buffers messages so that the timestamp in the filename is always valid. Additionally, it exposes the `TimeInfoReady` property that can be used to trigger messages only once a valid timestamp is available.

**Comment by paulbarron85** [comment]
> As a side note, you could simplify the logic of your first logging by leveraging the built-in string builder and any-to-`string` casts:
> 
> ```
> _logger
> 	.OnCondition(bFirstScan)
>         .AppendString('Initial value is ')
>         .AppendAny(bInput)
> 	.Warning();
> ```

Only problem here is that it prints bool True as 1 and False as 0. I prefer it to print True/False.
