### ISSUE TITLE
Problem with TwinCAT Build 4024.55

### ISSUE THREAD

**Issue by agilom** [bengeisler/TcLog#21]
Has anyone tested it with the current TwinCAT version. Our project does not build anymore after the upgrade.

**Comment by seehma** [comment]
Hi,
have you tried to reference TcLog-Library with qualified access only in References? Iam not sure if that has changed much in TwinCAT 3.1.4024.55 but this could lead to an error because of main FB has same name as the library itself...
![grafik](https://github.com/bengeisler/TcLog/assets/7335330/5b6f751b-9d53-47b2-a8c6-e3104314df3f)

If you set this to True, you will have to provide the namespace (TcLog.) to every type you use out of the library e.g.
![grafik](https://github.com/bengeisler/TcLog/assets/7335330/40c4dab7-fd01-4cfb-9dbe-6c11d3759b5c)

I have installed it via [Twinpack](https://github.com/zeugwerk/twinpack), changed that setting to True, updated all uses and this works fine for me...
Regards
M.

**Comment by agilom** [comment]
With the 'Qualified access only' set to true its working again. Thanks for your quick response!

**Comment by makitagawa243** [comment]
I encount same problem with TwinCAT 4024.56.
I would like to hope note in README that'Qualified access only' set to true if build fails.

**Comment by bengeisler** [comment]
With the [latest release](https://github.com/bengeisler/TcLog/releases/tag/v0.5.0) the namespace has changed to `TcLogLib`. This fixed this issue.
